Remove unused header from client.c
It fixes client-only builds. Like currently libcouchbase does. Without
patch 'make distcheck' of libcouchbase is complaining like this:

   CC       contrib/cbsasl/src/libcbsasl_la-client.lo
 ../contrib/cbsasl/src/client.c:20:31: fatal error: cram-md5/cram-md5.h: No such file or directory
 #include "cram-md5/cram-md5.h"
                               ^

Change-Id: I4d126c672717ad7c24311503fc3d1c3066a6ea2d
Reviewed-on: http://review.couchbase.org/29738
Tested-by: Sergey Avseyev <sergey.avseyev@gmail.com>
Reviewed-by: Trond Norbye <trond.norbye@gmail.com>